# Generated by Django 3.1.7 on 2021-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20210326_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
